version: 2

project_name: today

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: today
    main: .
    binary: today
    ldflags:
      - -s -w
      - -X github.com/mholtzscher/today/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: "checksums.txt"

changelog:
  use: github-native

brews:
  - name: today
    repository:
      owner: mholtzscher
      name: homebrew-tap
      token: "{{ .Env.PAT }}"
    directory: Formula
    homepage: "https://github.com/mholtzscher/today"
    description: "A Go CLI tool built with Nix"
    license: "MIT"
    install: |
      bin.install "today"
    test: |
      system "#{bin}/today", "--version"


release:
  github:
    owner: mholtzscher
    name: today
  prerelease: auto
  name_template: "v{{.Version}}"
