// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Entry struct {
	ID         int64         `json:"id"`
	Text       string        `json:"text"`
	CreatedAt  int64         `json:"created_at"`
	ArchivedAt sql.NullInt64 `json:"archived_at"`
}
