// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Entry struct {
	ID         int64          `json:"id"`
	Text       string         `json:"text"`
	CreatedAt  sql.NullString `json:"created_at"`
	ArchivedAt interface{}    `json:"archived_at"`
}
