// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const archiveEntry = `-- name: ArchiveEntry :execrows
UPDATE entries
SET archived_at = datetime('now')
WHERE id = ? AND archived_at IS NULL
`

func (q *Queries) ArchiveEntry(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveEntry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createEntry = `-- name: CreateEntry :exec
INSERT INTO entries (text)
VALUES (?)
`

func (q *Queries) CreateEntry(ctx context.Context, text string) error {
	_, err := q.db.ExecContext(ctx, createEntry, text)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT id, text, created_at, archived_at
FROM entries
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listEntriesSince = `-- name: ListEntriesSince :many
SELECT id, text, created_at, archived_at
FROM entries
WHERE date(created_at) >= date('now', CAST(? AS TEXT))
AND archived_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListEntriesSince(ctx context.Context, dollar_1 string) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesSince, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesSinceAll = `-- name: ListEntriesSinceAll :many
SELECT id, text, created_at, archived_at
FROM entries
WHERE date(created_at) >= date('now', CAST(? AS TEXT))
ORDER BY created_at DESC
`

func (q *Queries) ListEntriesSinceAll(ctx context.Context, dollar_1 string) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesSinceAll, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreEntry = `-- name: RestoreEntry :execrows
UPDATE entries
SET archived_at = NULL
WHERE id = ? AND archived_at IS NOT NULL
`

func (q *Queries) RestoreEntry(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreEntry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
