// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Entry struct {
	ID        int64          `json:"id"`
	Text      string         `json:"text"`
	CreatedAt string         `json:"created_at"`
	DeletedAt sql.NullString `json:"deleted_at"`
}

type User struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
}
